import { event } from 'jquery';
import React, { Component, useState } from 'react';
import Blog from './Blog';
import Card from './Card';
import Card2 from './Card2';
import Carousel from './Carousel';
import Footer from './Footer';
import Pagination from './Pagination';

function Content(props) {
    let news2 = new Array();
    if(props.category!="All News"){
        news2 = (props.news || []).filter(data => data.category == props.category)
    }
    else{
        news2 = props.news;
    }

    const [begin,setBegin] = useState(0);
    const [end,setEnd] = useState(begin+3);
    const pageNum = news2.length/3;

    
    const listNews = news2.slice(begin,end).map((neew) =>
    <Card key={neew.title} new = {neew} />);

    const handleBeginChange=event=>{
        setBegin(event.target.id*3);
        setEnd((event.target.id*3)+3);
        event.preventDefault();
      }





        return (
            <div className="container mt-4" >
                <div className="row-12">
                    <Carousel/>
                </div>
                <div className="row mt-3">
                    <div className="col-7">
                    <h3>{props.category}</h3>
                    {listNews}
                    <Pagination begin = {begin} end = {end} pageNum={pageNum} handleBeginChange = {handleBeginChange}/>
                    </div>
                    <div className="col-5">
                    <h3>Blogs</h3>
                    <Blog date="19.02.2020" time="10:23" author="Akerke Sultanova" image="https://img.lovepik.com/element/40144/5345.png_860.png" blogText="Like many Swedish parents, Mr Rääf deals with the constant stream of laundry generated by his two small children by using the larger communal washers available in his apartment block, alongside the machine in his own flat."   />
                
                    </div>
                </div>
                
            </div>
        );
}

export default Content;